name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set MSBuild Path
      run: echo "MSBUILD_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_ENV

    #- name: Restore NuGet packages
    # run: nuget restore

    - name: Build Automation.Framework.Core.WebUI
      run: ${{ env.MSBUILD_PATH }}\MSBuild.exe /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:ProjectFile=Automation.Framework.Core.WebUI.csproj

    - name: Build AutomationRunner
      run: ${{ env.MSBUILD_PATH }}\MSBuild.exe /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:ProjectFile=AutomationRunner.csproj

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MyProject
        path: |
          ./Automation.Framework.Core.WebUI/bin/Release
          ./AutomationRunner/bin/Release
